"""Configuration module for the Sotkanet Health Dashboard."""

from .settings import (
    ENV,
    INDICATOR_IDS,
    HUS_REGION_ID,
    DEFAULT_YEARS,
    DEFAULT_LANGUAGE,
    SOTKANET_BASE_URL,
    API_TIMEOUT,
    API_RETRY_COUNT,
    API_RETRY_DELAY,
    CACHE_ENABLED,
    CACHE_TTL,
    CACHE_DIR,
    LOG_LEVEL,
    LOG_DIR,
    METADATA_FILE,
    VALIDATION_RESULTS_FILE,
    INDICATORS_METADATA,
    get_indicator_metadata,
    get_all_indicator_ids,
    get_environment,
    require_metadata,
)

__all__ = [
    'ENV',
    'INDICATOR_IDS',
    'HUS_REGION_ID',
    'DEFAULT_YEARS',
    'DEFAULT_LANGUAGE',
    'SOTKANET_BASE_URL',
    'API_TIMEOUT',
    'API_RETRY_COUNT',
    'API_RETRY_DELAY',
    'CACHE_ENABLED',
    'CACHE_TTL',
    'CACHE_DIR',
    'LOG_LEVEL',
    'LOG_DIR',
    'METADATA_FILE',
    'VALIDATION_RESULTS_FILE',
    'INDICATORS_METADATA',
    'get_indicator_metadata',
    'get_all_indicator_ids',
    'get_environment',
    'require_metadata',
]